version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    command: ["postgres", "-c", "shared_preload_libraries=vector"]

volumes:
  postgres_data:
    driver: local